export interface dataType  {
    "id": number,
    "title": string,
    "slug": string,
    "permalink": string,
    "template": string,
    "parent": boolean,
    "content": string,
    "acf": {
        "competence": [
            {
                "nom_competence": string,
                "liens_page_competence": string
            }
        ],
        "slide": [
            {
                "image": {
                    "ID": number,
                    "id": number,
                    "title": string,
                    "filename": string,
                    "filesize": number,
                    "url": string,
                    "link": string,
                    "alt": string,
                    "author": string,
                    "description": string,
                    "caption": string,
                    "name": string,
                    "status": string,
                    "uploaded_to": number,
                    "date": string,
                    "modified": string,
                    "menu_order": number,
                    "mime_type": string,
                    "type": string,
                    "subtype": string,
                    "icon": string,
                    "width": number,
                    "height": number,
                    "sizes": {
                        "thumbnail": string,
                        "thumbnail-width": number,
                        "thumbnail-height": number,
                        "medium": string,
                        "medium-width": number,
                        "medium-height": number,
                        "medium_large": string,
                        "medium_large-width": number,
                        "medium_large-height": number,
                        "large": string,
                        "large-width": number,
                        "large-height": number,
                        "1536x1536": string,
                        "1536x1536-width": number,
                        "1536x1536-height": number,
                        "2048x2048": string,
                        "2048x2048-width": number,
                        "2048x2048-height": number,
                        "imgBlog": string,
                        "imgBlog-width": number,
                        "imgBlog-height": number
                    }
                }
            },
        ],
        "texte_photo": string,
        "texte_competences": string,
        "poles_de_competences": [
            {
                "icone": {
                    "ID": number,
                    "id": number,
                    "title": string,
                    "filename": string,
                    "filesize": number,
                    "url": string,
                    "link": string,
                    "alt": string,
                    "author": string,
                    "description": string,
                    "caption": string,
                    "name": string,
                    "status": string,
                    "uploaded_to": number,
                    "date": string,
                    "modified": string,
                    "menu_order": number,
                    "mime_type": string,
                    "type": string,
                    "subtype": string,
                    "icon": string,
                    "width": number,
                    "height": number,
                    "sizes": {
                        "thumbnail": string,
                        "thumbnail-width": number,
                        "thumbnail-height": number,
                        "medium": string,
                        "medium-width": number,
                        "medium-height": number,
                        "medium_large": string,
                        "medium_large-width": number,
                        "medium_large-height": number,
                        "large": string,
                        "large-width": number,
                        "large-height": number,
                        "1536x1536": string,
                        "1536x1536-width": number,
                        "1536x1536-height": number,
                        "2048x2048": string,
                        "2048x2048-width": number,
                        "2048x2048-height": number,
                        "imgBlog": string,
                        "imgBlog-width": number,
                        "imgBlog-height": number
                    }
                },
                "titre": string,
                "descriptif": string,
                "liens_competences": string
            },
        ],
        "texte_philosophie": string,
        "image_philosophie": string,
        "texte_methodologie":string,
        "titre_newsletter": string,
        "texte_newsletter": string
    },
}